- name: Demo on Ply level variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}

 #In Ansible variables will be accessed usin {{}}
 #Ansible supports double quotes and single quotes. However quotes are not mandatory in all the casess
 # Quotes are mandatory if value starts with a varibale, meaning
 # msg: {{ URL }} <-- This require quotes
#msg: URL - {{ URL }}  <-- This doesn't require quotes

- name: Load variables from a file
  hosts: all
  vars_files:
    - exvars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}

#varfile doesn't suport task level and it supports only play level

- name: Demo on Ply level variables
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}
      vars:
        URL: tasks.example.com
#task variables can't access by other tasks

#varibale from roles

- name: Variable from Roles
  hosts: all
  vars:
    URL_Play: play.example.com

  roles:
    - sample
