- name: Demo on Play level variable
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}

# Task level variable

- name: Demo on task level variable
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}
      vars:
        URL: playtask.example.com

#Load variables from a file

- name: Load variables from a file
  hosts: all
  vars_files:
    - exvars.yml
  tasks:
    - name: Print URL from file var file
      ansible.builtin.debug:
        msg: URL - {{ URL }}

#variable from roles
- name: Variable from roles
  hosts: all
  vars:
    PLAY_URL : Play.Role.example.com
  roles:
    - sample